all: 
  children:
    docker_swarm:
      children:
        manager:
          hosts:
            swarm_manager:
              ansible_host: 10.103.45.150
              ansible_user: vm
              ansible_become_pass: password
        worker:
          hosts:
            worker_1:
              ansible_host: 10.103.45.149
              ansible_user: vm
              ansible_become_pass: password           
            worker_2:
              ansible_host: 10.103.45.148
              ansible_user: vm
              ansible_become_pass: password