vms:
  manager-1:
    ip: 192.168.56.2
    cpus: 1
    memory: 2048
  manager-2:
    ip: 192.168.56.3
    cpus: 1
    memory: 2048
  manager-3:
    ip: 192.168.56.4
    cpus: 1
    memory: 2048

  worker-1:
    ip: 192.168.56.5
    cpus: 2
    memory: 4096
  worker-2:
    ip: 192.168.56.6
    cpus: 2
    memory: 4096
  worker-3:
    ip: 192.168.56.7
    cpus: 2
    memory: 4096
  worker-4:
    ip: 192.168.56.8
    cpus: 2
    memory: 4096
  worker-5:
    ip: 192.168.56.9
    cpus: 2
    memory: 4096