version: 3
images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:latest
dependencies:
  system:
    - openssh-clients
    - sshpass
  galaxy:
    collections:
      - name: community.docker
